sky:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    host: localhost
    port: 3306
    database: sky_take_out
    username: root
    password: axz520
  alioss:
    endpoint: oss-cn-beijing.aliyuncs.com
    access-key-id: LTAI5t8QdWN7DUAWU6H96Q3z
    access-key-secret: QrzKPya2BYXjOG0upuczlAvjDpTXdB
    bucket-name: axz-axz
